// static String baseUrl = 'https://story-api.dicoding.dev/v1';
// const baseUrl = 'http://127.0.0.1:8000/api';
const baseUrl = 'http://192.168.1.12:8000/api'; //hp
const loginUrl = '$baseUrl/login';
const registerUrl = '$baseUrl/register';
const logoutUrl = '$baseUrl/logout';
const postUrl = '$baseUrl/posts';
const newsUrl = '$baseUrl/news';
const jadwalUrl = '$baseUrl/jadwal';
const nilaiUrl = '$baseUrl/nilai';
const bayarUrl = '$baseUrl/bayar';
const fotoUrl = '$baseUrl/image';
