const baseUrl = 'https://api.smkpsukaraja.sch.id/api';
// const baseUrl = 'http://192.168.1.12:8000/api'; //hp
const loginUrl = '$baseUrl/login';
const registerUrl = '$baseUrl/register';
const logoutUrl = '$baseUrl/logout';
const postUrl = '$baseUrl/posts';
const newsUrl = '$baseUrl/news';
const jadwalUrl = '$baseUrl/jadwal';
const nilaiUrl = '$baseUrl/nilai';
const bayarUrl = '$baseUrl/bayar';
const fotoUrl = '$baseUrl/image';
